#!/bin/bash

echo "-i -o -- *  required"

set -e

BIN_PATH=$(readlink -f "$0")
FUZZ_DIR=$(dirname $BIN_PATH)

FUZZER="${FUZZ_DIR}/afl-fuzz"

sancmd=$(echo $* | sed 's,\.afl,\.san,g')
subject=$(echo $* | sed 's,.*subjects\/,,g')
subject=$(echo ${subject} | sed 's,\.afl.*,,g')


cmd="${FUZZER} -M 1 -d -r ./subjects/${subject}.func -a ./FInfos/func-${subject} $* &> /dev/null &"

echo $cmd
eval $cmd


cmd="${FUZZER} -S 2 -r ./subjects/${subject}.func -a ./FInfos/func-${subject} ${sancmd} &> /dev/null &"
echo $cmd
eval $cmd

cmd="${FUZZER} -S 3 -r ./subjects/${subject}.func -a ./FInfos/func-${subject} -c ./subjects/${subject}.cmp $* &> /dev/null &"
echo $cmd
eval $cmd

cmd="${FUZZER} -S 4 -r ./subjects/${subject}.func -a ./FInfos/func-${subject} $* &> /dev/null &"
echo $cmd
eval $cmd

cmd="${FUZZER} -S 5 -r ./subjects/${subject}.func -a ./FInfos/func-${subject} $*"
echo $cmd
eval $cmd
