#!/bin/bash
# -i -o -- *  required

trap "exit" INT TERM ERR
trap "kill 0" EXIT

BIN_PATH=$(readlink -f "$0")
FUZZ_DIR=$(dirname $BIN_PATH)

FUZZER="${FUZZ_DIR}/afl-fuzz"

sancmd=$(echo $* | sed 's,\.afl,\.san,g')
subject=$(echo $* | sed 's,.*subjects\/,,g')
subject=$(echo ${subject} | sed 's,\.afl.*,,g')

export AFL_DISABLE_TRIM=1

cmd="gdb --batch --command=test.gdb --args ${FUZZER} -M 1 -d -r ./subjects/${subject}.func -a ./FInfos/func-${subject} $* &> gdb1.log &"
echo $cmd
AFL_NO_UI=1 eval $cmd


cmd="gdb --batch --command=test.gdb --args ${FUZZER} -S 2 -r ./subjects/${subject}.func -a ./FInfos/func-${subject} ${sancmd} &> gdb2.log &"
echo $cmd
AFL_NO_UI=1 eval $cmd

cmd="gdb --command=test.gdb --args ${FUZZER} -S 3 -r ./subjects/${subject}.func -a ./FInfos/func-${subject} $*"
echo $cmd
eval $cmd

wait
