#!/bin/bash

echo "-i -o -r funcexec -a funcinfo -- *  required"

set -e

BIN_PATH=$(readlink -f "$0")
FUZZ_DIR=$(dirname $BIN_PATH)

FUZZER="${FUZZ_DIR}/afl-fuzz"

cmd="${FUZZER} -M 1 -d $* &> /dev/null &"

echo $cmd
eval $cmd

sancmd=$(echo $* | sed 's,\.afl,\.san,g')
cmpexe=$(echo $* | sed 's,.*-- ,,g')
cmpexe=$(echo ${cmpexe} | sed 's,\.afl.*,,g')

cmd="${FUZZER} -S 2 ${sancmd} &> /dev/null &"
echo $cmd
eval $cmd

cmd="${FUZZER} -S 3 -c ${cmpexe}.cmp $* &> /dev/null &"
echo $cmd
eval $cmd

cmd="${FUZZER} -S 4 $* &> /dev/null &"
echo $cmd
eval $cmd

cmd="${FUZZER} -S 5 $*"
echo $cmd
eval $cmd
